use std::path::PathBuf;
use std::sync::Arc;

use crate::ca::Ca;
use crate::routes::BootstrapTokens;
use zhiwei_storage::Storage;

#[derive(Clone)]
pub struct AppState {
    pub storage: Storage,
    /// Data directory (when changing credentials, write back to `<data-dir>/admin.token`)
    pub data_dir: PathBuf,
    pub ca: Arc<Ca>,
    pub ca_cert_pem: String,
    pub bootstrap_tokens: Arc<BootstrapTokens>,
    /// Browser-facing credential for the read API (nodes use request signing, not this).
    /// Console credentials. Can be changed (settings page "change password"), so in RwLock.
    pub admin_token: Arc<std::sync::RwLock<String>>,
    /// ops control plane public key (base64). Distributed to nodes during enroll for TOFU;
    /// ops private key only exists within ops-server process, monitor doesn't hold it,
    /// therefore cannot forge commands.
    pub ops_public_key: String,
    /// ops-server local address (console initiates commands, monitor forwards to it for signing)
    pub ops_endpoint: String,
    /// Nonces used by node request signing, for replay protection
    pub nonce_cache: Arc<zhiwei_common::NonceCache>,
    #[allow(dead_code)]
    pub server_cert_cn: String,
    /// Whether TLS is terminated by this process.
    ///
    /// When false (`--plain-http`, e.g. deployed behind edge TLS termination platforms like Render),
    /// **enroll does not distribute local CA**: that CA has no relation to the proper certs used by
    /// the edge. Once pinned, every request after enroll fails TLS verification.
    pub tls_terminated_locally: bool,
    /// Console build directory (if present, served by monitor, provides SPA fallback for index.html)
    pub ui_dir: Option<PathBuf>,
    /// Help page markdown content (loaded from `assets/help.md` at startup)
    pub help: crate::state::HelpContent,
    /// Base URL for MCP server calling its own REST APIs,
    /// format `http://127.0.0.1:8443`. See `mcp.rs`.
    pub mcp_base_url: String,
    /// Node enrollment install script body (embedded at compile time from `scripts/install-node.sh`,
    /// served verbatim by `GET /install-node.sh`).
    pub install_script: String,
    /// Optional self-hosted node binary distribution source (from `ZHIWEI_NODE_BASE_URL`).
    ///
    /// When set, enrollment commands generated by the console automatically include
    /// `ZHIWEI_BASE_URL=<this value>`,
    /// so nodes don't need to pull binaries from GitHub Releases. Useful for domestic /
    /// isolated network deployments: set once on your monitor, all enrollment commands naturally use
    /// the self-hosted source, without requiring each executor to remember the extra variable.
    pub node_base_url: Option<String>,
    /// Command persisted signal: watch stores an incrementing "generation" counter. Node long-polls subscribe
    /// to it, wake up as soon as signing succeeds -- reduces "click delete -> node executes" from
    /// up to 10s to under 1s.
    ///
    /// Commands are always forwarded by this process to ops for signing, so persistence timing
    /// is observable within the process; the long-poll still has periodic DB polling as
    /// fallback for edge cases like multi-instance (see routes::collect_pending).
    pub command_signal: tokio::sync::watch::Sender<u64>,
    /// Last time each node pulled commands -- sole evidence of "is the command channel still alive?" See
    /// [`crate::control_channel`].
    pub control_polls: Arc<crate::control_channel::ControlPolls>,
    /// This process start time (milliseconds). Any judgment based only on in-memory evidence must
    /// first pass the observation window, otherwise every restart would report the whole world as failed.
    pub started_at_ms: i64,
}

impl AppState {
    /// After issuing a command, wake all nodes in long-poll. Value itself is meaningless,
    /// only "it changed" signals new commands.
    pub fn notify_command(&self) {
        self.command_signal.send_modify(|v| *v = v.wrapping_add(1));
    }
}

/// Help markdown content per locale (loaded from `assets/help.{locale}.md`
/// at startup). Missing locales fall back to zh-CN; an empty map means UI
/// shows a placeholder.
#[derive(Clone, Default)]
pub struct HelpContent(pub Arc<std::sync::RwLock<HelpInner>>);

#[derive(Default)]
pub struct HelpInner {
    /// Map of locale ("zh-CN" / "en-US") → markdown body. First entry wins
    /// when no locale is requested.
    pub by_locale: std::collections::BTreeMap<String, String>,
    /// Which locale is the implicit default when none is requested.
    pub default_locale: String,
}

impl HelpContent {
    /// Build from a `(locale, body)` list; first entry becomes the default
    /// when callers don't pass `Accept-Language` / `?locale=` (typically zh-CN
    /// is loaded first, so it stays the implicit fallback).
    pub fn new(entries: impl IntoIterator<Item = (String, String)>) -> Self {
        let mut by_locale = std::collections::BTreeMap::new();
        let mut default_locale = String::new();
        for (i, (locale, body)) in entries.into_iter().enumerate() {
            if i == 0 {
                default_locale = locale.clone();
            }
            by_locale.insert(locale, body);
        }
        Self(Arc::new(std::sync::RwLock::new(HelpInner {
            by_locale,
            default_locale,
        })))
    }
    /// Snapshot for a specific locale. Unknown / missing locale falls back
    /// to the default; an entirely empty map yields empty body so the UI
    /// can render its "not loaded" placeholder.
    pub fn snapshot_for(&self, locale: Option<&str>) -> HelpSnapshot {
        let g = self.0.read().unwrap_or_else(|e| e.into_inner());
        let resolved = locale
            .and_then(|l| g.by_locale.get_key_value(l))
            .map(|(l, _)| l.clone())
            .unwrap_or_else(|| {
                if g.by_locale.contains_key(&g.default_locale) {
                    g.default_locale.clone()
                } else {
                    // empty map — synthesize locale string so UI still knows
                    g.default_locale.clone()
                }
            });
        let body = g
            .by_locale
            .get(&resolved)
            .cloned()
            .unwrap_or_default();
        HelpSnapshot {
            locale: resolved,
            body,
        }
    }
    /// Snapshot using the default locale (kept for back-compat / tests).
    #[allow(dead_code)]
    pub fn snapshot(&self) -> HelpSnapshot {
        self.snapshot_for(None)
    }
}

#[derive(serde::Serialize)]
pub struct HelpSnapshot {
    pub locale: String,
    pub body: String,
}
